// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yprowuaupnwspobugmox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwcm93dWF1cG53c3BvYnVnbW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjYxNTcsImV4cCI6MjA3MDcwMjE1N30.C46f2qBbeVJHqqgL5ZBidxzPYRiyylzvCSWW1sHYwM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});